Repository IPPL-framework/ippl, pull requests merged in 2023-09, with the labels that each got.

#215 Particle attribute internal buffer for MPI communication
  alpine/BumponTailInstability.cpp
  alpine/ChargedParticles.hpp
  alpine/LandauDamping.cpp
  alpine/LandauDampingMixedExec.cpp
  alpine/LandauDampingMixedPrecision.cpp
  alpine/PenningTrap.cpp
  alpine/UniformPlasmaTest.cpp
  src/Particle/ParticleAttrib.h
  src/Particle/ParticleAttrib.hpp
  src/Particle/ParticleAttribBase.h
  src/Particle/ParticleBase.h
  src/Particle/ParticleBase.hpp
  src/Particle/ParticleSpatialLayout.h
  src/Particle/ParticleSpatialLayout.hpp
  test/particle/PICnd.cpp
  test/particle/TestGather.cpp
  test/particle/TestScatter.cpp
  test/particle/benchmarkParticleUpdate.cpp
  unit_tests/PIC/ORB.cpp
  unit_tests/PIC/PIC.cpp
  unit_tests/Particle/ParticleSendRecv.cpp
Labels: enhancement

#219 Vector class: add variadic template constructor and dot product function
  src/Types/Vector.h
  src/Types/Vector.hpp
  test/vector/TestVector.cpp
Labels: feature request

#220 ParticleBase: add member variable totalNum_m
  src/Particle/ParticleBase.h
  src/Particle/ParticleBase.hpp
  src/Particle/ParticleSpatialLayout.hpp
Labels: feature request

#223 Cast variadic arguments and enable constructor only if argument number matches dimension
  src/Types/Vector.h
  src/Types/Vector.hpp
Labels: bug, enhancement

#224 Add scalar vector operations
  src/Types/Vector.h
  src/Types/Vector.hpp
  test/vector/TestVector.cpp
Labels: feature request

#217 Fix template parameters for CIC
  src/Interpolation/CIC.h
  src/Interpolation/CIC.hpp
  src/Particle/ParticleAttrib.hpp
Labels: bug
