Repository IPPL-framework/ippl, pull requests merged in 2023-11, with the labels that each got.

#233 Update unit test framework
  CMakeLists.txt
  CMakeModules/FindGTest.cmake
  unit_tests/BareField/CMakeLists.txt
  unit_tests/FFT/CMakeLists.txt
  unit_tests/Field/CMakeLists.txt
  unit_tests/Meshes/CMakeLists.txt
  unit_tests/PIC/CMakeLists.txt
  unit_tests/Particle/CMakeLists.txt
  unit_tests/Utility/CMakeLists.txt
Labels: enhancement, cleanup, unit test

#239 add isParallelDim_m assignment
  src/FieldLayout/FieldLayout.hpp
Labels: bug

#232 127 nearest neighbor loop
  src/Particle/ParticleSpatialLayout.h
  src/Particle/ParticleSpatialLayout.hpp
  src/Types/Vector.h
  src/Types/Vector.hpp
Labels: enhancement

#229 First implementation of Distribution and InversteTransformSampling cl…
  alpine/FieldContainer.hpp
  alpine/FieldSolver.hpp
  alpine/LandauDamping.cpp
  alpine/LandauDampingManager.h
  alpine/LoadBalancer.hpp
  alpine/ParticleContainer.hpp
  alpine/PenningTrap.cpp
  alpine/PenningTrapManager.h
  src/Manager/CMakeLists.txt
  src/Manager/FieldSolverBase.h
  src/Manager/PicManager.h
  src/Random/CMakeLists.txt
  src/Random/Distribution.h
  src/Random/InverseTransformSampling.h
  src/Random/NormalDistribution.h
  src/Random/Randn.h
  src/Random/Randu.h
  src/Random/UniformDistribution.h
  src/Random/Utility.h
  test/random/TestInverseTransformSamplingCustom.cpp
  test/random/TestInverseTransformSamplingNormal.cpp
  test/random/TestUnboundedNormal.cpp
Labels: feature request
