Repository IPPL-framework/ippl, pull requests merged in 2024-05, with the labels that each got.

#286 fix tags
  src/Communicate/Tags.h
Labels: bug

#281 Rewrite CMakeLists.txt
  CMakeLists.txt
  README.md
  alpine/ExamplesWithoutPicManager/CMakeLists.txt
  src/CMakeLists.txt
  test/random/TestInverseTransformSamplingCustom.cpp
  test/types/CMakeLists.txt
Labels: enhancement

#284 Disable LaTeX Documentation
  .github/workflows/main.yml
  .gitignore
  doc/Doxyfile
  doc/examples/BasicsSolver.hpp
  doc/examples/CustomPreconditioner.hpp
  doc/examples/CustomSolver.hpp
  doc/extras/Basics.md
Labels: documentation

#298 Add warmup to FFT periodic solver and P3M
  src/PoissonSolvers/FFTPeriodicPoissonSolver.hpp
  src/PoissonSolvers/P3MSolver.hpp
Labels: enhancement
